export const southAfricanLanguages = [
  'English',
  'isiZulu',
  'isiXhosa',
  'Afrikaans',
  'Sepedi',
  'Setswana',
  'Sesotho',
  'Xitsonga',
  'siSwati',
  'Tshivenda',
  'isiNdebele',
]

export const educationLevels = [
  'Grade R',
  'Grade 1',
  'Grade 2',
  'Grade 3',
  'Grade 4',
  'Grade 5',
  'Grade 6',
  'Grade 7',
  'Grade 8',
  'Grade 9',
  'Grade 10',
  'Grade 11',
  'Grade 12',
  'University',
  'College',
  'Self-learning',
]

export const southAfricanSubjects = [
  'Mathematics',
  'Physical Sciences',
  'Life Sciences',
  'Accounting',
  'Geography',
  'History',
  'English',
  'Afrikaans',
  'isiZulu',
  'Business Studies',
  'Economics',
  'CAT',
  'IT',
  'Tourism',
  'Mathematical Literacy',
  'Engineering Graphics',
  'University subjects',
]

export const learningModes = [
  'Homework help',
  'Explain in simple terms',
  'Quiz mode',
  'Test prep',
  'Exam mode',
  'Interactive examples',
]

export const explanationDepths = ['Quick explanation', 'Step-by-step', 'Deep concept walkthrough']

export const developerLanguages = [
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C',
  'C++',
  'C#',
  'Go',
  'Rust',
  'PHP',
  'Swift',
  'Kotlin',
  'Dart',
  'Ruby',
  'SQL',
  'HTML',
  'CSS',
  'Bash',
  'PowerShell',
  'Lua',
  'R',
  'Scala',
  'Perl',
  'Objective-C',
  'Assembly',
]

export const developerFrameworks = [
  'None',
  'React',
  'Next.js',
  'Vue',
  'Angular',
  'Svelte',
  'Node.js',
  'Express',
  'Django',
  'Flask',
  'FastAPI',
  'Spring',
  'Laravel',
  'Rails',
  '.NET',
  'Flutter',
]

export const developerWorkflows = [
  'Format code',
  'Explain code',
  'Debug',
  'Optimize',
  'Generate comments',
  'Convert language',
  'Compare diff',
  'API test',
]
